// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    IconLowVision: typeof import('~icons/icon/low-vision')['default']
    Jaw: typeof import('./src/components/jaw.vue')['default']
  }
}

export { }
